export const mockProducts = [
  // Smartphones
  {
    id: 1,
    name: "UltraPhone 15",
    price: 899,
    rating: 4.8,
    store: "TechStore",
    category: "Smartphones",
    deliveryDays: 2,
    reliability: 98,
    inStock: true,
    image: "📱",
    description: "Premium smartphone with advanced AI features, 5G connectivity, and exceptional camera quality.",
    specs: {
      display: "6.7 inch AMOLED",
      processor: "Latest generation AI chipset",
      camera: "200MP main + 12MP ultra-wide",
      battery: "4500mAh with fast charging",
      ram: "12GB LPDDR5",
      storage: "256GB UFS",
    },
    reviews: [
      {
        author: "Alex K.",
        rating: 5,
        text: "Absolutely amazing phone! Camera quality is outstanding.",
        date: "2024-01-15",
      },
      { author: "Maria S.", rating: 4, text: "Great performance, but battery could last longer.", date: "2024-01-10" },
      {
        author: "John D.",
        rating: 5,
        text: "Fast delivery and exactly as described. Highly recommend!",
        date: "2024-01-05",
      },
    ],
  },
  {
    id: 2,
    name: "UltraPhone 15",
    price: 879,
    rating: 4.7,
    store: "ElectroMart",
    category: "Smartphones",
    deliveryDays: 3,
    reliability: 96,
    inStock: true,
    image: "📱",
    description: "Premium smartphone with advanced AI features, 5G connectivity, and exceptional camera quality.",
    specs: {
      display: "6.7 inch AMOLED",
      processor: "Latest generation AI chipset",
      camera: "200MP main + 12MP ultra-wide",
      battery: "4500mAh with fast charging",
      ram: "12GB LPDDR5",
      storage: "256GB UFS",
    },
    reviews: [
      { author: "Emma L.", rating: 5, text: "Best price I found! Seller was very responsive.", date: "2024-01-14" },
      {
        author: "Chris M.",
        rating: 4,
        text: "Good phone, minor scratches on arrival but working perfectly.",
        date: "2024-01-08",
      },
    ],
  },
  {
    id: 3,
    name: "UltraPhone 15",
    price: 920,
    rating: 4.9,
    store: "DigitalHub",
    category: "Smartphones",
    deliveryDays: 1,
    reliability: 99,
    inStock: true,
    image: "📱",
    description: "Premium smartphone with advanced AI features, 5G connectivity, and exceptional camera quality.",
    specs: {
      display: "6.7 inch AMOLED",
      processor: "Latest generation AI chipset",
      camera: "200MP main + 12MP ultra-wide",
      battery: "4500mAh with fast charging",
      ram: "12GB LPDDR5",
      storage: "256GB UFS",
    },
    reviews: [
      { author: "Sarah B.", rating: 5, text: "Fastest delivery ever! Product is pristine.", date: "2024-01-13" },
      { author: "Mike T.", rating: 5, text: "Premium quality, exactly what I needed.", date: "2024-01-09" },
      { author: "Lisa R.", rating: 4, text: "Excellent phone, slight screen reflection issue.", date: "2024-01-03" },
    ],
  },
  {
    id: 4,
    name: "BudgetPhone X1",
    price: 399,
    rating: 4.5,
    store: "ValueTech",
    category: "Smartphones",
    deliveryDays: 4,
    reliability: 94,
    inStock: true,
    image: "📱",
    description: "Affordable smartphone with solid performance for everyday use.",
    specs: {
      display: "6.1 inch IPS LCD",
      processor: "Mid-range chipset",
      camera: "48MP main + 8MP ultra-wide",
      battery: "4000mAh",
      ram: "6GB",
      storage: "128GB",
    },
    reviews: [
      { author: "Tom H.", rating: 5, text: "Great value for money!", date: "2024-01-12" },
      { author: "Diana P.", rating: 4, text: "Good performance, not as fast as premium models.", date: "2024-01-07" },
    ],
  },

  // Tablets
  {
    id: 5,
    name: "ProTablet X",
    price: 599,
    rating: 4.6,
    store: "TechStore",
    category: "Tablets",
    deliveryDays: 3,
    reliability: 97,
    inStock: true,
    image: "📑",
    description: "Powerful tablet for professionals with stunning display and long battery life.",
    specs: {
      display: "11-inch Liquid Retina XDR",
      processor: "Advanced M-series chip",
      camera: "12MP wide + 12MP ultra-wide",
      battery: "10000mAh",
      ram: "8GB",
      storage: "256GB",
    },
    reviews: [
      { author: "Robert J.", rating: 5, text: "Perfect for design work. Display is incredible!", date: "2024-01-11" },
      { author: "Susan K.", rating: 4, text: "Great tablet, a bit pricey but worth it.", date: "2024-01-06" },
    ],
  },
  {
    id: 6,
    name: "ProTablet X",
    price: 579,
    rating: 4.5,
    store: "ShopHub",
    category: "Tablets",
    deliveryDays: 4,
    reliability: 95,
    inStock: true,
    image: "📑",
    description: "Powerful tablet for professionals with stunning display and long battery life.",
    specs: {
      display: "11-inch Liquid Retina XDR",
      processor: "Advanced M-series chip",
      camera: "12MP wide + 12MP ultra-wide",
      battery: "10000mAh",
      ram: "8GB",
      storage: "256GB",
    },
    reviews: [
      { author: "Paul F.", rating: 5, text: "Cheaper than other stores, arrived quickly!", date: "2024-01-10" },
      { author: "Nancy W.", rating: 4, text: "Good product, delivery took longer than expected.", date: "2024-01-04" },
    ],
  },
  {
    id: 7,
    name: "BudgetTablet Plus",
    price: 349,
    rating: 4.3,
    store: "BudgetTech",
    category: "Tablets",
    deliveryDays: 5,
    reliability: 92,
    inStock: true,
    image: "📑",
    description: "Affordable tablet for entertainment and browsing.",
    specs: {
      display: "10.5-inch IPS LCD",
      processor: "Entry-level chipset",
      camera: "8MP",
      battery: "7000mAh",
      ram: "4GB",
      storage: "64GB",
    },
    reviews: [{ author: "Gary M.", rating: 4, text: "Good budget option for basic tasks.", date: "2024-01-09" }],
  },

  // Headphones
  {
    id: 8,
    name: "NoiseCancel Pro",
    price: 299,
    rating: 4.7,
    store: "AudioWorld",
    category: "Headphones",
    deliveryDays: 2,
    reliability: 96,
    inStock: true,
    image: "🎧",
    description: "Premium noise-cancelling headphones with superior sound quality.",
    specs: {
      driver: "40mm dynamic driver",
      frequency: "20Hz - 20kHz",
      battery: "30 hour battery life",
      weight: "250g",
      connectivity: "Bluetooth 5.3 + 3.5mm",
    },
    reviews: [
      {
        author: "Vincent L.",
        rating: 5,
        text: "Best headphones I've ever owned. Noise cancellation is perfect!",
        date: "2024-01-12",
      },
      { author: "Rachel G.", rating: 4, text: "Great sound, a bit heavy for long sessions.", date: "2024-01-08" },
    ],
  },
  {
    id: 9,
    name: "NoiseCancel Pro",
    price: 319,
    rating: 4.8,
    store: "SoundHub",
    category: "Headphones",
    deliveryDays: 2,
    reliability: 98,
    inStock: true,
    image: "🎧",
    description: "Premium noise-cancelling headphones with superior sound quality.",
    specs: {
      driver: "40mm dynamic driver",
      frequency: "20Hz - 20kHz",
      battery: "30 hour battery life",
      weight: "250g",
      connectivity: "Bluetooth 5.3 + 3.5mm",
    },
    reviews: [
      { author: "Oscar N.", rating: 5, text: "Excellent headphones, highly reliable seller!", date: "2024-01-11" },
    ],
  },
  {
    id: 10,
    name: "BudgetHeadphones X",
    price: 79,
    rating: 4.1,
    store: "AudioBudget",
    category: "Headphones",
    deliveryDays: 3,
    reliability: 90,
    inStock: true,
    image: "🎧",
    description: "Budget-friendly headphones with decent sound quality.",
    specs: {
      driver: "32mm driver",
      frequency: "20Hz - 18kHz",
      battery: "15 hour battery life",
      weight: "160g",
      connectivity: "Bluetooth 5.0",
    },
    reviews: [{ author: "Tyler Q.", rating: 4, text: "Good for the price!", date: "2024-01-07" }],
  },

  // Wearables
  {
    id: 11,
    name: "SmartWatch Ultra",
    price: 449,
    rating: 4.6,
    store: "WearTech",
    category: "Wearables",
    deliveryDays: 3,
    reliability: 94,
    inStock: false,
    image: "⌚",
    description: "Advanced smartwatch with health tracking and fitness features.",
    specs: {
      display: "1.9 inch AMOLED",
      processor: "Dual-core processor",
      battery: "4 day battery",
      water_resistance: "50m",
      sensors: "ECG, SpO2, temperature",
    },
    reviews: [
      {
        author: "Kevin Z.",
        rating: 5,
        text: "Amazing smartwatch! Health tracking is very accurate.",
        date: "2024-01-10",
      },
      { author: "Amanda C.", rating: 4, text: "Great features but out of stock, had to wait.", date: "2024-01-06" },
    ],
  },
  {
    id: 12,
    name: "FitnessWatch Pro",
    price: 199,
    rating: 4.4,
    store: "FitGear",
    category: "Wearables",
    deliveryDays: 2,
    reliability: 95,
    inStock: true,
    image: "⌚",
    description: "Fitness-focused smartwatch with comprehensive health tracking.",
    specs: {
      display: "1.4 inch AMOLED",
      processor: "Single-core",
      battery: "7 day battery",
      water_resistance: "50m",
      sensors: "Heart rate, SpO2, sleep tracking",
    },
    reviews: [
      {
        author: "Sophia E.",
        rating: 4,
        text: "Good fitness tracker, battery lasts longer than premium models.",
        date: "2024-01-09",
      },
    ],
  },

  // Accessories
  {
    id: 13,
    name: "PowerBank 30K",
    price: 89,
    rating: 4.7,
    store: "PowerSource",
    category: "Accessories",
    deliveryDays: 2,
    reliability: 97,
    inStock: true,
    image: "🔋",
    description: "High-capacity power bank for extended device charging.",
    specs: {
      capacity: "30000mAh",
      output: "2x USB-C + 1x USB-A",
      charging_speed: "65W fast charging",
      weight: "680g",
      warranty: "18 months",
    },
    reviews: [
      { author: "Brandon U.", rating: 5, text: "Charges my phone multiple times! Very reliable.", date: "2024-01-11" },
    ],
  },
  {
    id: 14,
    name: "PowerBank 30K",
    price: 79,
    rating: 4.5,
    store: "BudgetTech",
    category: "Accessories",
    deliveryDays: 5,
    reliability: 92,
    inStock: true,
    image: "🔋",
    description: "High-capacity power bank for extended device charging.",
    specs: {
      capacity: "30000mAh",
      output: "2x USB-C + 1x USB-A",
      charging_speed: "65W fast charging",
      weight: "680g",
      warranty: "12 months",
    },
    reviews: [
      { author: "Melissa V.", rating: 4, text: "Great value, slightly heavier than expected.", date: "2024-01-08" },
    ],
  },
  {
    id: 15,
    name: "USB-C Cable 2m",
    price: 19,
    rating: 4.6,
    store: "AccessoryHub",
    category: "Accessories",
    deliveryDays: 1,
    reliability: 98,
    inStock: true,
    image: "🔌",
    description: "Durable USB-C cable with fast charging support.",
    specs: {
      length: "2 meters",
      power_delivery: "100W",
      connector: "Gold-plated",
      material: "Braided nylon",
      warranty: "Lifetime",
    },
    reviews: [
      { author: "Henry W.", rating: 5, text: "Perfect cable! Fast delivery and great quality.", date: "2024-01-12" },
    ],
  },

  // Laptops
  {
    id: 16,
    name: "Laptop Pro M4",
    price: 1899,
    rating: 4.9,
    store: "ComputerWorld",
    category: "Laptops",
    deliveryDays: 2,
    reliability: 99,
    inStock: true,
    image: "💻",
    description: "Powerful laptop for professionals and creators.",
    specs: {
      processor: "M4 Max chip",
      memory: "24GB unified memory",
      storage: "512GB SSD",
      display: "16-inch Liquid Retina XDR",
      battery: "Up to 18 hours",
    },
    reviews: [
      {
        author: "Jennifer X.",
        rating: 5,
        text: "Best laptop I've ever used. Perfect for video editing!",
        date: "2024-01-13",
      },
      { author: "David Y.", rating: 5, text: "Excellent build quality and performance.", date: "2024-01-09" },
    ],
  },
  {
    id: 17,
    name: "Laptop Pro M4",
    price: 1850,
    rating: 4.8,
    store: "TechDeals",
    category: "Laptops",
    deliveryDays: 3,
    reliability: 97,
    inStock: true,
    image: "💻",
    description: "Powerful laptop for professionals and creators.",
    specs: {
      processor: "M4 Max chip",
      memory: "24GB unified memory",
      storage: "512GB SSD",
      display: "16-inch Liquid Retina XDR",
      battery: "Up to 18 hours",
    },
    reviews: [
      {
        author: "Patricia Z.",
        rating: 5,
        text: "Great deal! Saved money compared to other stores.",
        date: "2024-01-11",
      },
    ],
  },
  {
    id: 18,
    name: "BudgetLaptop i7",
    price: 799,
    rating: 4.4,
    store: "ValueTech",
    category: "Laptops",
    deliveryDays: 4,
    reliability: 93,
    inStock: true,
    image: "💻",
    description: "Affordable laptop for everyday computing and light work.",
    specs: {
      processor: "Intel Core i7",
      memory: "8GB DDR4",
      storage: "256GB SSD",
      display: "15.6-inch FHD",
      battery: "8 hours",
    },
    reviews: [{ author: "Frank A.", rating: 4, text: "Good budget laptop for daily use.", date: "2024-01-10" }],
  },
]
